function createfiguresynlog(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-May-2021 09:43:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,...
    'MarkerIndices',[1:10:1000],...
    'LineWidth',3,...
    'Parent',axes1);
set(loglog1(1),'DisplayName','GradientGreedy','Marker','*');
set(loglog1(2),'DisplayName','Gradient RepGreedy','Marker','o',...
    'LineStyle','-.');
set(loglog1(3),'DisplayName','ExtraGradient Greedy','MarkerSize',8,...
    'Marker','diamond');
set(loglog1(4),'DisplayName','ExtraGradient RepGreedy',...
    'MarkerIndices',[1:10:1000],...
    'LineStyle','-.');

% Create ylabel
ylabel('log(\phi(x_t))','FontName','Times New Roman');

% Create xlabel
xlabel('log(t)','FontName','Times New Roman');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',30,'XMinorTick','on',...
    'XScale','log','YMinorTick','on','YScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.594347826086958 0.683689024390244 0.281739130434783 0.194359756097561]);

